title = "Project configuration"

[model]

input_size = 10
output_size = 3

[training]

n_epochs = 3
batch_size_train = 64
batch_size_test = 1000
learning_rate = 0.01
momentum = 0.5
log_interval = 10

[random]

seed = 1